services:
  - type: web
    name: wardrobe-backend
    env: python
    buildCommand: ./build.sh
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: "0"
